FROM node:18.14.2

# Définir le répertoire de travail
WORKDIR /app

# Copiez package.json et package-lock.json (s'il existe) dans le répertoire de travail
COPY package.json package-lock.json* ./

# Installer les dépendances
RUN npm install

# Copier tous les fichiers dans le répertoire de travail
COPY . .

# Exposez le port sur lequel votre application Vite s'exécutera
EXPOSE 5173

# Démarrer le serveur de développement
CMD ["npm", "run", "dev"]
