FROM node:18.14.2
WORKDIR /app
COPY ./package.json ./
RUN npm i
COPY . .
EXPOSE 3001

# Installer les dépendances de construction
RUN apt-get update && \
    apt-get install -y build-essential && \
    apt-get clean

# Reconstruire bcrypt (bibliothèque de chiffrement de mot de passe)
RUN npm rebuild bcrypt --build-from-source

CMD ["npm", "run", "dev"]
